sensor_kit_base_link:
# camera
  traffic_light_left_camera:
    x: 1.118
    y: -0.045
    z: -0.169
    roll: -1.624
    pitch: 0.051 
    yaw: -1.486
  camera1:
    x: 1.118
    y: -0.045
    z: -0.169
    roll: -1.624
    pitch: 0.051 
    yaw: -1.486
  
  zed:
    x: 0.787
    y: -0.031
    z: 1.065
    roll: 0.008
    pitch: 0.292
    yaw: 0.020
# combined navigation
  gnss:
    x: -0.37
    y: 0.0
    z: 0.18
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

# lidar
  # The laser coordinate system is the y-axis toward the front of the car.
  # robobus -- muti lidar
  os_sensor_top:
    x: 0.00
    y: -0.000
    z: 1.8
    roll: 0.0
    pitch: 0.0
    yaw: 3.10
  os_sensor_ancillary:
    x: 5.645 
    y: 0.411
    z: -1.174
    roll: -0.003
    pitch: 0.014
    yaw: 0.050
  # robobus -- muti lidar
  os_sensor_fl:
    x: 1.16941
    y: 1.0914 
    z: -0.44231 
    roll: -0.0231962 
    pitch: 0.268778
    yaw: 1.24752 
  os_sensor_fr:
    x: 1.29626
    y: -0.921884
    z: -0.415867
    roll: -3.13429
    pitch: 2.87074
    yaw:  1.97643
  os_sensor_rl:
    x: -1.22306
    y: 0.945165
    z: -0.452872  
    roll: 0.0316878
    pitch: 0.26885 
    yaw: 1.98253
  os_sensor_rr:
    x: -1.10474
    y: -0.966971
    z: -0.452921
    roll: 3.11137
    pitch: 2.88721
    yaw: 1.24932

# millimeter wave
  front_radar:
    x: 1.2
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  rear_radar:
    x: -1.2
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 3.1416