sensor_kit_base_link:
# camera
  traffic_light_left_camera:
    x: 1.080
    y: 0.173
    z: -0.016
    roll: -1.572
    pitch: -0.017
    yaw: -1.590
  zed:
    x: 0.787
    y: -0.031
    z: 1.065
    roll: 0.008
    pitch: 0.292
    yaw: 0.020
# combined navigation
  gnss:
    x: -0.37
    y: 0.0
    z: 0.18
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

# lidar
  # The laser coordinate system is the y-axis toward the front of the car.
  os_sensor_top:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  # robobus -- muti lidar
  os_sensor_fl:
    x: 1.829
    y: 1.104
    z: -0.419
    roll: -0.029
    pitch: 0.012
    yaw: 0.086
  os_sensor_fr:
    x: 1.963
    y: -0.822
    z: -0.513
    roll: -3.130
    pitch: 0.021
    yaw: 0.105
  os_sensor_rl:
    x: -1.886
    y: 0.763
    z: -0.463
    roll: -3.124
    pitch: 0.010
    yaw: -3.040
  os_sensor_rr:
    x: -1.775
    y: -1.044
    z: -0.428
    roll: 0.029
    pitch: 0.020
    yaw: -3.123

# millimeter wave
  front_radar:
    x: 1.2
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  rear_radar:
    x: -1.2
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 3.1416