sensing/lidar/front_left/ouster/os_sensor:
# ouster/os_sensor:
  ros__parameters:
    sensor_hostname: '192.168.1.120'
    udp_dest: ''
    mtp_dest: ''
    mtp_main: false
    lidar_mode: ''
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: ''
    metadata: ''
    lidar_port: 0
    imu_port: 0
sensing/lidar/front_left/ouster/os_cloud:
# ouster/os_cloud:
  ros__parameters:
    sensor_frame: 'os_sensor_fl'
    lidar_frame: 'os_lidar_fl'
    imu_frame: 'os_imu_fl'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
